# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application  # Name of the workflow

on:  # Specifies when the workflow should be triggered
  push:  # Trigger the workflow on a push event
    branches: [ "*" ]  # Runs for the any branch
  pull_request:  # Trigger the workflow on a pull request event
    branches: [ "*" ]  # Runs for pull requests of any branch

permissions:  # Sets permissions for the workflow
  contents: read  # Grants read access to the repository's contents

jobs:  # Defines a collection of jobs
  build:  # Name of the job

    runs-on: ubuntu-latest  # Specifies the type of virtual host machine to run this job on

    steps:  # Sequence of tasks to be executed
    - uses: actions/checkout@v3  # Checks out the repository under $GITHUB_WORKSPACE, so the workflow can access it
    - name: Set up Python 3.10  # Name of the step
      uses: actions/setup-python@v3  # Sets up a specific Python version for use in actions
      with:
        python-version: "3.10"  # Specifies the Python version to set up
    - name: Install dependencies
      run: | # Installs dependencies
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install .
    - name: Lint with flake8
      run: |  # Run a series of commands for linting
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |  # Run the pytest command to execute tests
        pytest -v